version: "3"

vars: {}

env: {}

tasks:
  virtualenv:
    desc: Synchronize Python virtual environment using uv package manager
    cmds:
      - uv sync

  run:
    deps:
      - virtualenv
    desc: Execute the main.py script to generate data profiling reports
    cmds:
      - uv run main.py

  consolidate:
    deps:
      - virtualenv
    desc: Consolidate the data profiling reports into a single report
    cmds:
      - uv run consolidate_reports.py

  clean:
    desc: Remove all generated reports from the reports directory
    cmds:
      - cmd: rm -rf reports/*
        ignore_error: true
      - cmd: rm -rf consolidated_reports/*
        ignore_error: true
